### ISSUE TITLE
Sanity clean-up

### ISSUE THREAD

**Issue by lovisegit** [oslopride/europride#27]
Remove these sections in sanity:
- Venue
- Author
- Livestream
- Posts (?) Do we need that one when we have "Articles"?
- Need a place to add the program-events? 

Can we rename "Configuration" to "Website". And then remove the "App, areas, venues".

**Comment by atfilipcc** [comment]
- removed venue/location/arena/app/livestream/post
- we should keep author if we want to support articles.
- we already have an "events"-schema that runs on the program page

**Comment by atfilipcc** [comment]
I removed author, just going to use volunteer instead
